/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package trabalhopratico;

/**
 *
 * @author lgdsc
 */
public class SistemaBancario extends javax.swing.JFrame {

    /** Creates new form SistemaBancario */
    public SistemaBancario() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        ManterClientes = new javax.swing.JTabbedPane();
        Clientes = new javax.swing.JPanel();
        CadC = new javax.swing.JPanel();
        labelNome_Cadc = new javax.swing.JLabel();
        labelSobrenome_Cadc = new javax.swing.JLabel();
        labelRG_Cadc = new javax.swing.JLabel();
        labelCPF_CadC = new javax.swing.JLabel();
        labelDadosPessoaisTit_Cadc = new javax.swing.JLabel();
        textNome_Cadc = new javax.swing.JTextField();
        textSobrenome_Cadc = new javax.swing.JTextField();
        textRG_Cadc = new javax.swing.JTextField();
        textCPF_Cadc = new javax.swing.JTextField();
        labelEnderecoTit_CadC = new javax.swing.JLabel();
        labelCEP_CadC = new javax.swing.JLabel();
        labelLogradouro_CadC = new javax.swing.JLabel();
        labelComplemento_CadC = new javax.swing.JLabel();
        textCEP_CadC = new javax.swing.JTextField();
        btnBuscaCEP = new javax.swing.JButton();
        textLogradouro_CadC = new javax.swing.JTextField();
        labelNumeroPredial_CadC = new javax.swing.JLabel();
        textNumeroPredial_CadC = new javax.swing.JTextField();
        textComplemento_CadC = new javax.swing.JTextField();
        labeBairro_CadC = new javax.swing.JLabel();
        textBairro_CadC = new javax.swing.JTextField();
        labelCidade_CadC = new javax.swing.JLabel();
        textCidade_CadC = new javax.swing.JTextField();
        labelUF_CadC = new javax.swing.JLabel();
        textUF_CadC = new javax.swing.JTextField();
        btnValidarCPF = new javax.swing.JButton();
        btnLimparNome_CadC = new javax.swing.JButton();
        btnCadastrar_CadC = new javax.swing.JButton();
        btnLimparEnd_CadC = new javax.swing.JButton();
        resultValidaCPF_CadC = new javax.swing.JLabel();
        labelRenda_CadC = new javax.swing.JLabel();
        textRenda_CadC = new javax.swing.JTextField();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jTabbedPane4 = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        org.jdesktop.layout.GroupLayout ClientesLayout = new org.jdesktop.layout.GroupLayout(Clientes);
        Clientes.setLayout(ClientesLayout);
        ClientesLayout.setHorizontalGroup(
            ClientesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 1009, Short.MAX_VALUE)
        );
        ClientesLayout.setVerticalGroup(
            ClientesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 471, Short.MAX_VALUE)
        );

        ManterClientes.addTab("Clientes", Clientes);

        labelNome_Cadc.setText("Nome:");

        labelSobrenome_Cadc.setText("Sobrenome:");

        labelRG_Cadc.setText("RG:");

        labelCPF_CadC.setText("CPF:");

        labelDadosPessoaisTit_Cadc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelDadosPessoaisTit_Cadc.setText("Dados pessoais");

        labelEnderecoTit_CadC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelEnderecoTit_CadC.setText("Endereço");

        labelCEP_CadC.setText("CEP:");

        labelLogradouro_CadC.setText("Logradouro:");

        labelComplemento_CadC.setText("Complemento:");

        btnBuscaCEP.setText("Busca pelo CEP");

        labelNumeroPredial_CadC.setText("Número Predial:");

        labeBairro_CadC.setText("Bairro:");

        labelCidade_CadC.setText("Cidade:");

        labelUF_CadC.setText("UF:");

        btnValidarCPF.setText("Validar CPF");

        btnLimparNome_CadC.setText("Limpar");

        btnCadastrar_CadC.setText("Cadastrar");

        btnLimparEnd_CadC.setText("Limpar");

        labelRenda_CadC.setText("Renda:");

        org.jdesktop.layout.GroupLayout CadCLayout = new org.jdesktop.layout.GroupLayout(CadC);
        CadC.setLayout(CadCLayout);
        CadCLayout.setHorizontalGroup(
            CadCLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(CadCLayout.createSequentialGroup()
                .add(CadCLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(CadCLayout.createSequentialGroup()
                        .add(62, 62, 62)
                        .add(CadCLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(labelNome_Cadc)
                            .add(labelRG_Cadc)
                            .add(labelCPF_CadC)
                            .add(labelRenda_CadC))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(CadCLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(CadCLayout.createSequentialGroup()
                                .add(CadCLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, btnLimparNome_CadC)
                                    .add(textCPF_Cadc, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 274, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(btnValidarCPF)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(resultValidaCPF_CadC, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .add(CadCLayout.createSequentialGroup()
                                .add(CadCLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(textRG_Cadc, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 274, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(CadCLayout.createSequentialGroup()
                                        .add(CadCLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                            .add(org.jdesktop.layout.GroupLayout.LEADING, textRenda_CadC, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                                            .add(org.jdesktop.layout.GroupLayout.LEADING, textNome_Cadc))
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(labelSobrenome_Cadc)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(textSobrenome_Cadc, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 274, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                                .add(0, 0, Short.MAX_VALUE))))
                    .add(CadCLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(labelDadosPessoaisTit_Cadc, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 180, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, CadCLayout.createSequentialGroup()
                        .add(0, 12, Short.MAX_VALUE)
                        .add(CadCLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(labelEnderecoTit_CadC)
                            .add(CadCLayout.createSequentialGroup()
                                .add(17, 17, 17)
                                .add(CadCLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                    .add(labelCEP_CadC)
                                    .add(labelComplemento_CadC))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(CadCLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(CadCLayout.createSequentialGroup()
                                        .add(btnLimparEnd_CadC)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .add(btnCadastrar_CadC))
                                    .add(CadCLayout.createSequentialGroup()
                                        .add(CadCLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                            .add(org.jdesktop.layout.GroupLayout.LEADING, textComplemento_CadC)
                                            .add(org.jdesktop.layout.GroupLayout.LEADING, CadCLayout.createSequentialGroup()
                                                .add(textCEP_CadC, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 120, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                .add(btnBuscaCEP)))
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                        .add(CadCLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                            .add(CadCLayout.createSequentialGroup()
                                                .add(labelLogradouro_CadC)
                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                .add(textLogradouro_CadC, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 427, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                .add(labelNumeroPredial_CadC))
                                            .add(CadCLayout.createSequentialGroup()
                                                .add(labeBairro_CadC)
                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                .add(textBairro_CadC, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 161, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                .add(labelCidade_CadC)
                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                .add(textCidade_CadC, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 328, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(CadCLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                            .add(textNumeroPredial_CadC, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 82, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(CadCLayout.createSequentialGroup()
                                                .add(labelUF_CadC)
                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                .add(textUF_CadC, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 55, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))))))))
                .addContainerGap())
        );
        CadCLayout.setVerticalGroup(
            CadCLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(CadCLayout.createSequentialGroup()
                .addContainerGap()
                .add(labelDadosPessoaisTit_Cadc)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(CadCLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(labelNome_Cadc)
                    .add(textNome_Cadc, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(labelSobrenome_Cadc)
                    .add(textSobrenome_Cadc, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(CadCLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(labelRenda_CadC)
                    .add(textRenda_CadC, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(9, 9, 9)
                .add(CadCLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(labelRG_Cadc)
                    .add(textRG_Cadc, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(CadCLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(labelCPF_CadC)
                    .add(textCPF_Cadc, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(btnValidarCPF)
                    .add(resultValidaCPF_CadC, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(btnLimparNome_CadC)
                .add(16, 16, 16)
                .add(labelEnderecoTit_CadC)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(CadCLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(labelCEP_CadC)
                    .add(textCEP_CadC, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(btnBuscaCEP)
                    .add(labelLogradouro_CadC)
                    .add(textLogradouro_CadC, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(labelNumeroPredial_CadC)
                    .add(textNumeroPredial_CadC, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(CadCLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(labelComplemento_CadC)
                    .add(textComplemento_CadC, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(labeBairro_CadC)
                    .add(textBairro_CadC, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(labelCidade_CadC)
                    .add(textCidade_CadC, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(labelUF_CadC)
                    .add(textUF_CadC, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(CadCLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(btnCadastrar_CadC)
                    .add(btnLimparEnd_CadC))
                .addContainerGap(182, Short.MAX_VALUE))
        );

        ManterClientes.addTab("Cadastrar novo Cliente", CadC);

        jTabbedPane1.addTab("Manter Clientes", ManterClientes);
        jTabbedPane1.addTab("Vincular Cliente a Conta", jTabbedPane3);
        jTabbedPane1.addTab("Operar Conta", jTabbedPane4);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SistemaBancario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SistemaBancario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SistemaBancario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SistemaBancario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SistemaBancario().setVisible(true);
            }
        });
    }

 /**
 * Método para verifica se determinado cpf é válido.
 * @param cpf - Uma String contendo o cpf.
 * @return true se o cpf é válido e false se não é válido.
 * @author FONTE: www.guj.com.br
 */
    public static boolean validaCpf(String xCPF) {
        try {
            int d1, d4, xx, nCount, resto, digito1, digito2;
            String Check;
            String Separadores = "/-.";
            d1 = 0;
            d4 = 0;
            xx = 1;

            for (nCount = 0; nCount < xCPF.length() - 2; nCount++) {
                String s_aux = xCPF.substring(nCount, nCount + 1);

                if (Separadores.indexOf(s_aux) == -1) {
                    d1 = d1 + (11 - xx) * Integer.valueOf(s_aux).intValue();
                    d4 = d4 + (12 - xx) * Integer.valueOf(s_aux).intValue();
                    xx++;
                }
            }

            resto = (d1 % 11);

            if (resto < 2) {
                digito1 = 0;
            } else {
                digito1 = 11 - resto;
            }

            d4 = d4 + 2 * digito1;
            resto = (d4 % 11);

            if (resto < 2) {
                digito2 = 0;
            } else {
                digito2 = 11 - resto;
            }

            Check = String.valueOf(digito1) + String.valueOf(digito2);

            String s_aux2 = xCPF.substring(xCPF.length() - 2, xCPF.length());

            if (s_aux2.compareTo(Check) != 0) {
                return false;
            }

            return true;

        } catch (Exception e) {
            return false;
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CadC;
    private javax.swing.JPanel Clientes;
    private javax.swing.JTabbedPane ManterClientes;
    private javax.swing.JButton btnBuscaCEP;
    private javax.swing.JButton btnCadastrar_CadC;
    private javax.swing.JButton btnLimparEnd_CadC;
    private javax.swing.JButton btnLimparNome_CadC;
    private javax.swing.JButton btnValidarCPF;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JLabel labeBairro_CadC;
    private javax.swing.JLabel labelCEP_CadC;
    private javax.swing.JLabel labelCPF_CadC;
    private javax.swing.JLabel labelCidade_CadC;
    private javax.swing.JLabel labelComplemento_CadC;
    private javax.swing.JLabel labelDadosPessoaisTit_Cadc;
    private javax.swing.JLabel labelEnderecoTit_CadC;
    private javax.swing.JLabel labelLogradouro_CadC;
    private javax.swing.JLabel labelNome_Cadc;
    private javax.swing.JLabel labelNumeroPredial_CadC;
    private javax.swing.JLabel labelRG_Cadc;
    private javax.swing.JLabel labelRenda_CadC;
    private javax.swing.JLabel labelSobrenome_Cadc;
    private javax.swing.JLabel labelUF_CadC;
    private javax.swing.JLabel resultValidaCPF_CadC;
    private javax.swing.JTextField textBairro_CadC;
    private javax.swing.JTextField textCEP_CadC;
    private javax.swing.JTextField textCPF_Cadc;
    private javax.swing.JTextField textCidade_CadC;
    private javax.swing.JTextField textComplemento_CadC;
    private javax.swing.JTextField textLogradouro_CadC;
    private javax.swing.JTextField textNome_Cadc;
    private javax.swing.JTextField textNumeroPredial_CadC;
    private javax.swing.JTextField textRG_Cadc;
    private javax.swing.JTextField textRenda_CadC;
    private javax.swing.JTextField textSobrenome_Cadc;
    private javax.swing.JTextField textUF_CadC;
    // End of variables declaration//GEN-END:variables

}
